"""
CTFFramework.

Autogenerated by cookiecutter-awesome-poetry.
"""

from .ctff import CTFF
from .challenge import Challenge
from .challenge_group import ChallengeGroup

__all__ = [
    "__version__",
    "Challenge",
    "ChallengeGroup",
    "CTFF",
]

__version__ = "0.1.0a"
